# Generated by Django 4.2.25 on 2026-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resumefile_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип'),
        ),
    ]
